# Build custom docker image
# Install Bun (js runtime)

FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04

# install Bun globally
RUN curl -fsSL https://bun.sh/install | BUN_INSTALL=/usr/local bash -s "bun-v1.0.30"
